name: ci

on:
  push:
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.8, 3.7]
        extras: [all, soap_api, orjson, cli]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: 1.1.6
    - run: poetry install --extras ${{ matrix.extras }}
    - run: poetry run pytest -v
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        extras: [all]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: 1.1.6
    - run: poetry install --extras ${{ matrix.extras }}
    - run: poetry run flake8
    - run: poetry run mypy --ignore-missing-imports .
    - run: poetry run isort --check --diff .
    - run: poetry run black --check --diff .
