name: codecov

on:
  push:
  pull_request:

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: 1.1.6
    - run: poetry install --extras all
    - run: poetry run pytest --cov=netsuite --cov-report=xml --cov-report=term
    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
